# House Market

Let's go a little further into python.

1. Download the four files “superficie.csv” / “nombre_de_sdb.csv” / “nombre_de_chambres.csv” / "house_price.csv"

2. Read the files and create the 4 corresponding Dataframes

In [1]:
import pandas as pd

In [2]:

df_Surface = pd.read_csv(r"house_market\superficie.csv",header=None)        # header = None -> ne prends pas la première ligne comme ligne d'en-tête
df_Bathrooms = pd.read_csv(r"house_market\nombre_de_sdb.csv",header=None)   # r"xxx" -> texte brut. Cela évite les erreurs comme \n (retour à la ligne) et autres.
df_Rooms = pd.read_csv(r"house_market\nombre_de_chambres.csv",header=None)
df_House_prices = pd.read_csv(r"house_market\house_price.csv",index_col=0)  # index_col = 0 -> la colonne 0 sert d'index.

In [3]:
print("Surface:")
display(df_Surface.head())
print()
print("Bathrooms:")
display(df_Bathrooms.head())
print()
print("Rooms:")
display(df_Rooms.head())
print()
print("House prices:")
display(df_House_prices.head())

Surface:

   0      1
0  0  28844
1  1  27667
2  2  14742
3  3  28089
4  4  11713

Bathrooms:

   0  1
0  0  2
1  1  1
2  2  1
3  3  3
4  4  1

Rooms:

   0  1
0  0  1
1  1  4
2  2  1
3  3  4
4  4  2

House prices:

   id  house_price
0  14    1918154.0
1  30     739142.0
2  70    1621938.0
3  77    1319862.0
4  50     146250.0

In [4]:
df_Surface.columns.to_list()

[0, 1]

3. Give a column name to the three datasets that don't have a header in the source file

In [5]:
df_Surface.columns = ["id","surface"]
df_Bathrooms.columns = ["id","bathrooms"]
df_Rooms.columns = ["id","rooms"]

In [6]:
print("Surface:")
display(df_Surface.head())
print()
print("Bathrooms:")
display(df_Bathrooms.head())
print()
print("Rooms:")
display(df_Rooms.head())
print()
print("House prices:")
display(df_House_prices.head())

Surface:

   id  surface
0   0    28844
1   1    27667
2   2    14742
3   3    28089
4   4    11713

Bathrooms:

   id  bathrooms
0   0          2
1   1          1
2   2          1
3   3          3
4   4          1

Rooms:

   id  rooms
0   0      1
1   1      4
2   2      1
3   3      4
4   4      2

House prices:

   id  house_price
0  14    1918154.0
1  30     739142.0
2  70    1621938.0
3  77    1319862.0
4  50     146250.0

4. Make an inner join of these four datasets into a single dataframe.

In [7]:
df_total = pd.merge(df_Surface,df_Bathrooms, on='id')
df_total = pd.merge(df_total,df_Rooms, on='id')
df_total = pd.merge(df_total,df_House_prices, on='id')
df_total.head()

   id  surface  bathrooms  rooms  house_price
0   0    28844          2      1    1421908.0
1   1    27667          1      4    1305091.0
2   2    14742          1      1     164373.0
3   3    28089          3      4    1441714.0
4   4    11713          1      2     108290.0

5. What is the average surface area of the houses in our dataset?

In [8]:
print(f"The average surface area is : {df_total['surface'].mean()}")

The average surface area is : 20439.77

6. What is the median and average number of rooms?

In [9]:
print(f"The average number of room is : {df_total['rooms'].mean()}, and the median number is : {df_total['rooms'].median()}")

The average number of room is : 2.42, and the median number is : 2.0

7. What is the average cost of a house?

In [10]:
print(f"The average cost of a house is {df_total["house_price"].mean():,.2f}".replace(","," ") +" $")

The average cost of a house is 767 747.87 $

8. What is the average cost of a house, depending on the number of rooms it has?

In [11]:
print("Rooms")
df_total.groupby("rooms")["house_price"].mean().round(2)

Rooms

rooms
1    980774.87
2    642086.26
3    645904.59
4    888045.63
Name: house_price, dtype: float64

10. The average cost per room doesn't tell us much. Let's try to categorize by size.

  - Create a new column in your dataset that we'll call home_size
Create five categories that respectively correspond to:
      - "very large" $=$ "a house larger than 25,000 sqrt_feet"
      - "large" $=$ "a house between 20,000 and 25,000 sqrt_feet"
      - "medium" $=$ "a house between 15,000 and 20,000 sqrt_feet"
      - "small" $=$ "a house between 10,000 and 15,000 sqrt_feet"
      - "very small" $=$ a house less than 10,000 sqrt_feet"

Fill in the corresponding rows in the house_size column.

In [12]:
df_total["house_size"] = df_total["surface"].apply(
    lambda x: "very small" if x < 10000 else  
              "small" if x < 15000 else
              "medium" if x < 20000 else
              "large" if x < 25000 else
              "very large"
)
df_total.head()

   id  surface  bathrooms  rooms  house_price  house_size
0   0    28844          2      1    1421908.0  very large
1   1    27667          1      4    1305091.0  very large
2   2    14742          1      1     164373.0       small
3   3    28089          3      4    1441714.0  very large
4   4    11713          1      2     108290.0       small

11. What is the average cost of a house depending on its size category?

In [13]:
df_total.groupby("house_size")["house_price"].mean().round(2).sort_values(ascending=False)

house_size
very large    1552456.06
large          732538.52
medium         325694.79
small          156138.69
Name: house_price, dtype: float64

 12. Apply the code below to view your result. What can you conclude?

In [14]:
import plotly.express as px
fig = px.scatter(df_total, x = "surface", y = "house_price", trendline = "ols")
fig.show()

There is a correlation between the surface area and the price of the house.